version: "3"
services:
  mongo:
     image: mongo:latest
     ports:
       - 27017:27017

  wexflow:
    image: aelassas/wexflow:latest
    depends_on:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./appsettings.json:/opt/wexflow/Wexflow.Server/appsettings.json
      - ./Wexflow:/opt/wexflow/Wexflow
      - ./WexflowTesting:/opt/wexflow/WexflowTesting

  wexflow-backend:
    image: danjellz/http-server
    ports:
          - 8011:8011
    volumes:
      - ./Backend:/public
    command:
      http-server --cors -p 8011