name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build Wexflow.Server.csproj
      run: dotnet build src/netcore/Wexflow.Server/Wexflow.Server.csproj --configuration Release
    - name: Build Wexflow.Clients.CommandLine.csproj
      run: dotnet build src/netcore/Wexflow.Clients.CommandLine/Wexflow.Clients.CommandLine.csproj --configuration Release
    - name: Build Wexflow.Scripts.LiteDB.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.LiteDB/Wexflow.Scripts.LiteDB.csproj --configuration Release
    - name: Build Wexflow.Scripts.MongoDB.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.MongoDB/Wexflow.Scripts.MongoDB.csproj --configuration Release
    - name: Build Wexflow.Scripts.RavenDB.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.RavenDB/Wexflow.Scripts.RavenDB.csproj --configuration Release       
    - name: Build Wexflow.Scripts.PostgreSQL.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.PostgreSQL/Wexflow.Scripts.PostgreSQL.csproj --configuration Release
    - name: Build Wexflow.Scripts.SQLServer.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.SQLServer/Wexflow.Scripts.SQLServer.csproj --configuration Release
    - name: Build Wexflow.Scripts.MySQL.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.MySQL/Wexflow.Scripts.MySQL.csproj --configuration Release
    - name: Build Wexflow.Scripts.SQLite.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.SQLite/Wexflow.Scripts.SQLite.csproj --configuration Release            
    - name: Build Wexflow.Scripts.Firebird.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.Firebird/Wexflow.Scripts.Firebird.csproj --configuration Release
    - name: Build Wexflow.Scripts.Oracle.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.Oracle/Wexflow.Scripts.Oracle.csproj --configuration Release
    - name: Build Wexflow.Scripts.MariaDB.csproj
      run: dotnet build src/netcore/Wexflow.Scripts.MariaDB/Wexflow.Scripts.MariaDB.csproj --configuration Release            
    - name: Build Wexflow.NetCore.Tests.csproj
      run: dotnet build src/tests/netcore/Wexflow.NetCore.Tests/Wexflow.NetCore.Tests.csproj --configuration Release
